services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    TLH\ContactBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']

    TLH\ContactBundle\Services\Messager:
        arguments: ['@twig', '@mailer', '@request_stack']
        public: true
        calls:
            - method: setParameters
              arguments: ['%tlh_contact%']
