language: php

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm

sudo: false
dist: trusty

env:
  global:
    - SYMFONY_VERSION=""

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
      env: SYMFONY_VERSION=3.3.*
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*
    - php: 7.0
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=4.1.*
    - php: 7.1
      env: SYMFONY_VERSION=4.4.*
    - php: 7.2
      env: SYMFONY_VERSION=3.4.*
    - php: 7.2
      env: SYMFONY_VERSION=4.4.*
    - php: 7.2
      env: SYMFONY_VERSION=5.0.*
    - php: 7.3
      env: SYMFONY_VERSION=3.4.*
    - php: 7.3
      env: SYMFONY_VERSION=4.4.*
    - php: 7.3
      env: SYMFONY_VERSION=5.0.*
#    - php: 7.4
#      env: SYMFONY_VERSION=3.4.*
#    - php: 7.4
#      env: SYMFONY_VERSION=4.4.*
  allow_failures:
    - php: hhvm

before_install:
  # Increase Memory Limit
  - phpenv config-add travis.php.ini

# Update composer, and update Symfony version depending on the matrix
before_script:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
  - composer update ${COMPOSER_FLAGS} --prefer-stable --no-interaction

# Run script and log coverage in the "build" directory
script:
  - vendor/bin/phpunit ./Tests/

# Send a notification to our email address
notifications:
  email:
    - symfony@tousleshoraires.fr
