language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

env:
  - SYMFONY_VERSION="2.8.*" 
  - SYMFONY_VERSION="3.0.*"
  - SYMFONY_VERSION="3.1.*"
  - SYMFONY_VERSION="3.2.*"
  - SYMFONY_VERSION="dev-master" DB=mysql

before_script:
  - |
    if [[ ${SYMFONY_VERSION} != 3.* || $PHP != 5.4 ]]; then
      composer create-project symfony/framework-standard-edition my_project_name "${SYMFONY_VERSION}"
    fi
  # - composer require symfony/http-foundation:${SYMFONY_VERSION}

notifications:
  email:
    - symfony@tousleshoraires.fr
