language: php

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache

php:
  # - 5.4
  # - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false
dist: trusty

env:
  global:
    - SYMFONY_VERSION=""

matrix:
  fast_finish: true
  include:
    # - php: 5.4
    #   env: SYMFONY_VERSION=2.8.*
    # - php: 5.5
    #   env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.0
    - php: 7.1
      env: SYMFONY_VERSION=3.1.*
    - php: 7.0
    - php: 7.1
      env: SYMFONY_VERSION=3.2.*
    - php: 7.0
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*
  allow_failures:
    - php: hhvm

# Update composer, and update Symfony version depending on the matrix
before_script:
  - composer selfupdate
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi
  - composer update ${COMPOSER_FLAGS} --prefer-stable --no-interaction

# Run script and log coverage in the "build" directory
script:
  - vendor/bin/phpunit ./Tests/

# Send a notification to our email address
notifications:
  email:
    - symfony@tousleshoraires.fr
